# Site settings
lang: ko-KR
title: kohii
description: ""
url: "https://blog.kohii.me"
baseurl: ""

# User settings
username: kohii
user_title: kohii - FrontEnd
email: oojm1210@naver.com
twitter_username: more_kohii
github_username: more-kohii
linkedin_public_url: jmoh-kohii # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: /assets/img/quagsire-blink.gif

# Favicon
favicon: images/favicon.png # Scriptor 테마에 맞게 경로를 설정해야 할 수 있습니다.

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Posts
    url: /posts/ # posts.html 페이지를 사용하도록 설정
  - text: Series
    url: /series/ # series.html 페이지를 사용하도록 설정
  - text: Tags
    url: /tags/ # tags.html 페이지를 사용하도록 설정
  - text: About
    url: /about/ # about.html 페이지를 사용하도록 설정
  - text: GitHub
    url: https://github.com/more-kohii

# The shortname for your Disqus site to enable comments.
disqus: "" # 비워두면 댓글 기능이 비활성화됩니다.

# Colors
accent_color: "#2d72d9"

# Site footer
footer:
  content: "&copy; kohii all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# exclude my node related stuff
exclude:
  [
    "package.json",
    "src",
    "node_modules",
    "Scriptor-Jekyll-Theme",
    "test.py",
    "notion_secret",
    "Gemfile.lock",
    "vendor",
  ]
